# Targets the evergreen latest release of ruby, truffleruby, and jruby
name: Current

permissions:
  contents: read

env:
  K_SOUP_COV_DO: false

on:
  push:
    branches:
      - 'main'
      - "*-stable"
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Tests ${{ matrix.ruby }}@${{ matrix.appraisal_name }}
    if: ${{ !contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}
    env: # $BUNDLE_GEMFILE - set at job level, so applies to all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}.gemfile
    strategy:
      matrix:
        include:
          # Ruby <whichever version is current, e.g., 3.4 as of 2025-07-12>
          - ruby: "ruby"
            appraisal_name: "r3"
            exec_cmd: "rake test"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest

          # truffleruby <whichever version is current, e.g., 24.1 as of 2025-07-12>
          - ruby: "truffleruby"
            appraisal_name: "r3"
            exec_cmd: "rake test"
            gemfile: "Appraisal.root"
            rubygems: default
            bundler: default

          # jruby <whichever version is current, e.g., 10.0 (targets Ruby 3.4 compatibility) as of 2025-07-12>
          - ruby: "jruby"
            appraisal_name: "r3"
            exec_cmd: "rake test"
            gemfile: "Appraisal.root"
            rubygems: default
            bundler: default

    steps:
      - name: Checkout
        if: ${{ !env.ACT || !startsWith(matrix.ruby, 'jruby') }}
        uses: actions/checkout@v5

      - name: Setup Ruby & RubyGems
        if: ${{ !env.ACT || !startsWith(matrix.ruby, 'jruby') }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: false

      # Raw `bundle` will use the BUNDLE_GEMFILE set to matrix.gemfile (i.e., Appraisal.root)
      # We need to do this first to get appraisal installed.
      # NOTE: This does not use the main Gemfile at all.
      - name: Install Root Appraisal
        if: ${{ !env.ACT || !startsWith(matrix.ruby, 'jruby') }}
        run: bundle
      - name: Appraisal for ${{ matrix.ruby }}@${{ matrix.appraisal_name }}
        if: ${{ !env.ACT || !startsWith(matrix.ruby, 'jruby') }}
        run: bundle exec appraisal ${{ matrix.appraisal_name }} bundle
      - name: Run ${{ matrix.exec_cmd }} on ${{ matrix.ruby }}@${{ matrix.appraisal_name }}
        if: ${{ !env.ACT || !startsWith(matrix.ruby, 'jruby') }}
        run: bundle exec appraisal ${{ matrix.appraisal_name }} bundle exec ${{ matrix.exec_cmd }}
